import "./globals.css";

import { Roboto } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import Cart from "public/icons/basket.svg";
import { CartIndicator } from "./client-components";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["cyrillic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <header className="flex items-center justify-between px-8 py-6 text-white bg-gray-1">
          <Link href="/" className="text-4xl font-bold">
            Билетопоиск
          </Link>
          <div className="flex items-center gap-2">
            <CartIndicator />
            <Link href="/cart">
              <Image src={Cart} alt="cart" />
            </Link>
          </div>
        </header>

        <div className="px-6 py-8 bg-white-secondary">{children}</div>
        <footer className="flex justify-between px-8 py-6 text-xl text-white bg-gray-1">
          <Link href="/question-answered">Вопросы-ответы</Link>
          <Link href="/about">О нас</Link>
        </footer>
      </body>
    </html>
  );
}
